services:
  frontend:
    build:
      context: ./web-peladaapp
      dockerfile: Dockerfile
      target: prod
    image: peladaapp-frontend:${TAG:-prod}
    ports:
      - 80:80
    volumes:
      - ./nginx/frontend.prod.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./api-peladaapp
      dockerfile: Dockerfile
    image: peladaapp-backend:${TAG:-prod}
    volumes:
      - ./data/peladaapp.db:/app/peladaapp.db