services:
  frontend:
    hostname: frontend
    environment:
      - PORT=8080
      - VITE_BACKEND_URL=http://backend:8000
    build:
      context: ./web-peladaapp
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./web-peladaapp/src:/app/src
      - ./web-peladaapp/public:/app/public
      - ./web-peladaapp/index.html:/app/index.html
      - ./web-peladaapp/vite.config.ts:/app/vite.config.ts
      - ./web-peladaapp/tsconfig.json:/app/tsconfig.json
      - ./web-peladaapp/tsconfig.app.json:/app/tsconfig.app.json
    depends_on:
      - backend

  backend:
    hostname: backend
    build:
      context: ./api-peladaapp
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api-peladaapp:/app

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
