services:
  frontend:
    restart: always
    hostname: frontend
    environment:
      - PORT=8080
      - LANG=en_US.UTF-8
    build:
      context: ./web-peladaapp
      dockerfile: Dockerfile
      target: dev
    volumes:
      - /app/node_modules
      - ./web-peladaapp:/app
    depends_on:
      - backend

  backend:
    restart: always
    hostname: backend
    environment:
      - APP_VERSION=development
      - LANG=en_US.UTF-8
      - PELADA_API_SECURITY_SIGNING_KEY=${PELADA_API_SECURITY_SIGNING_KEY}
    build:
      context: ./api-peladaapp
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api-peladaapp:/app


  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
