services:
  frontend:
    restart: always
    build:
      context: ./web-peladaapp
      dockerfile: Dockerfile
      target: prod
      args:
        - VITE_APP_VERSION=${TAG:-prod}
    image: peladaapp-frontend:${TAG:-prod}
    ports:
      - 80:80
    volumes:
      - ./nginx/frontend.prod.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./api-peladaapp
      dockerfile: Dockerfile
    image: peladaapp-backend:${TAG:-prod}
    environment:
      - DB_NAME=data/peladaapp.db
      - SKIP_MIGRATIONS=false
      - APP_VERSION=${TAG:-prod}
    volumes:
      - ./data:/app/data