services:
  frontend:
    restart: always
    image: ghcr.io/marlonchalegre/pelada-web:${TAG:-latest}
    ports:
      - 80:80
    volumes:
      - ./nginx/frontend.prod.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  backend:
    restart: always
    image: ghcr.io/marlonchalegre/pelada-api:${TAG:-latest}
    environment:
      - DB_NAME=data/peladaapp.db
      - SKIP_MIGRATIONS=false
      - APP_VERSION=${TAG:-latest}
      - PELADA_API_SECURITY_SIGNING_KEY=${PELADA_API_SECURITY_SIGNING_KEY}
      - LITESTREAM_ACCESS_KEY_ID=${LITESTREAM_ACCESS_KEY_ID}
      - LITESTREAM_SECRET_ACCESS_KEY=${LITESTREAM_SECRET_ACCESS_KEY}
      - LITESTREAM_BUCKET=${LITESTREAM_BUCKET}
      - LITESTREAM_ENDPOINT=${LITESTREAM_ENDPOINT}
    volumes:
      - ./data:/app/data
      - ./api-peladaapp/litestream.yml:/etc/litestream.yml:ro
